### ISSUE TITLE
HTML知识点问题A&Q

### ISSUE THREAD

**Issue by giscafer** [giscafer/blog#2]
问题收集于[网络](http://www.imooc.com/article/10027)，答案是个人整理，@giscafer（仅供学习参考，有不对之处请指出）
### 1、Doctype作用？严格模式与混杂模式如何区分？它们有何意义?

> <!DOCTYPE> 声明必须是 HTML 文档的第一行，位于 <html> 标签之前。
> <!DOCTYPE> 声明不是 HTML 标签；它是指示 web 浏览器关于页面使用哪个 HTML 版本进行编写的指令。
> 在 HTML 4.01 中，<!DOCTYPE> 声明引用 DTD，因为 HTML 4.01 基于 SGML。DTD 规定了标记语言的规则，这样浏览器才能正确地呈现内容。
> HTML5 不基于 SGML，所以不需要引用 DTD。
> 提示：请始终向 HTML 文档添加 <!DOCTYPE> 声明，这样浏览器才能获知文档类型。

**严格模式**
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">`
**混杂模式**
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
"http://www.w3.org/TR/html4/loose.dtd">`
- 区别：严格模式是浏览器根据规范去显示页面；混杂模式是以一种向后兼容的方式去显示
- 意义：决定浏览器如何渲染网站（浏览器使用那种规范去解析网页）
- 触发：浏览器根据doctype是否存在和使用的是那种dtd来决定。

[了解更多More](http://www.w3school.com.cn/tags/tag_doctype.asp)

---
### 2、HTML5 为什么只需要写 <!DOCTYPE HTML>？

 上边问题已经说，**HTML5 不基于 _SGML_，所以不需要引用 DTD。**

---
### 3、行内元素有哪些？块级元素有哪些？ 空(void)元素有那些？

CSS规范规定，每个元素都有`display`属性，确定该元素的类型，每个元素都有默认的display值，
 比如div默认display属性值为“block”，成为“块级”元素；
span默认display属性值为“inline”，是“行内”元素。  

行内元素有：`a b span img input select strong`（强调的语气） 
块级元素有：`div ul ol li dl dt dd h1 h2 h3 h4…p`

知名的空元素： 
`<br> <hr> <img> <input> <link> <meta>`
鲜为人知的空元素： 
`<area> <base> <col> <command> <embed> <keygen> <param> <source> <track> <wbr>`

---
### 4、页面导入样式时，使用link和@import有什么区别？
- **隶属上的差别**
  
  link属于HTML标签，而`@import`完全是CSS提供的一种方式。
- **`@import`次数限制**

`@import`只能引入31次css文件。
- **加载顺序的不同**
  
   当页面被加载的时候，link引用的CSS会同时被加载，而`@import`引用的CSS 会等到页面全部被下载完再被加载。所以有时候浏览`@import`加载CSS的页面时开始会没有样式，然后突然样式会出现，网速慢的时候还挺明显。
- **兼容性上的差别**
  
   由于`@import`是CSS2.1提出的，`@import`只有在IE5以上的才能识别，而link标签无此问题
- **使用DOM控制样式时的差别**
  
   当使用javascript控制DOM(document.styleSheets)去改变样式的时候，只能使用`link标签`，因为`@import`不是dom可以控制的。

[了解更多](http://blog.csdn.net/wy_0928/article/details/48111009)

---
### 5、介绍一下你对浏览器内核的理解？

那内核是什么呢？内核只是一个通俗的说法，其英文名称为“Layout engine”，翻译过来就是“排版引擎”，也被称为“页面渲染引擎”（下文中各种说法通用）。它负责取得网页的内容（HTML、XML、图像等等）、整理信息（例如加入CSS等），以及计算网页的显示方式，然后会输出至显示器或打印机。所有网页浏览器、电子邮件客户端以及其它需要编辑、显示网络内容的应用程序都需要排版引擎。
不同的浏览器内核对网页编写语法的解释也有不同，因此同一网页在不同的内核的浏览器里的渲染（显示）效果也可能不同，这也是网页编写者需要在不同内核的浏览器中测试网页显示效果的原因。
这就是编写网页的麻烦所在啊。。。要让所有浏览器显示大概一致，有时候很麻烦。

现在市面上常见的 内核基本是一下4种：

**Trident：**

这是微软开发的一种排版引擎。该内核程序在1997年的IE4中首次被采用，是微软在Mosaic代码的基础之上修改而来的，并沿用到目前的 IE7。Trident实际上是一款开放的内核，其接口内核设计的相当成熟，因此才有许多采用IE内核而非IE的浏览器涌现（如 Maxthon、The World 、TT、GreenBrowser、AvantBrowser等）。此外，为了方便也有很多人直接简称其为IE内核（当然也不排除有部分人是因为不知道内 核名称而只好如此说，至少老N就是如此。。。）。自从发布后，Trident不断地被更新和完善：

Trident II（IE5）——增进对CSS1.0的支持及对CSS2重大的变更；

Trident III（IE5.5）——修正部分CSS的排版控制；

Trident IV（IE6）——修正了一部分box-model的错误以及增加了“兼容模式（Quirks Mode）”切换功能，以增加对文件类型描述（Document Type Definition，DTD）的支持；

Trident V（IE7）——修正许多CSS排版处理上的错误以及增加对PNG格式alpha通道（半透明）的支持。（这就是IE6经常被诟病的对png图片支持不良的之处！）

**Geckos：**

Gecko是套开放源代码的、以C++编写的网页排版引擎。这软件原本是由网景通讯公司开发的，Netcape6开始采用该内核。后来的 Mozilla FireFox也采用了该内核，Geckos的特点是代码完全公开，因此，其可开发程度很高，全世界的程序员都可以为其编写代码，增加功能。Geckos 现在由Mozilla基金会维护。

**Presto：**

Presto是一个由Opera Software开发的浏览器排版引擎，该内核在2003年的Opera7中首次被使用，该款引擎的特点就是渲染速度的优化达到了极致，也是目前公认网页浏览速度最快的浏览器内核。

**Webkit：**

苹果公司自己的内核，也是苹果的Safari浏览器使用的内核。 Webkit引擎包含WebCore排版引擎及JavaScriptCore解析引擎，均是从KDE的KHTML及KJS引擎衍生而来，它们都是自由软 件，在GPL条约下授权，同时支持BSD系统的开发。所以Webkit也是自由软件，同时开发源代码。在安全方面不受IE、Firefox的制约，所以 Safari浏览器在国内还是很安全的。

**简单的总结一下：**
- 使用Trident内核的浏览器：IE、Maxthon、TT、The World等；
- 使用Gecko内核的浏览器：Netcape6及以上版本、FireFox、MozillaSuite/SeaMonkey；
- 使用Presto内核的浏览器：Opera7及以上版本；
- 使用Webkit内核的浏览器：Safari、Chrome。

_本问题答案来自[出处](http://www.cnblogs.com/fullhouse/archive/2012/01/17/2324724.html)_

_下边是获取浏览器信息的片段代码_

``` javascript
var browser = {
        versions: function () {
            var u = navigator.userAgent, app = navigator.appVersion;
            return {//移动终端浏览器版本信息
                trident: u.indexOf('Trident') > -1, //IE内核
                presto: u.indexOf('Presto') > -1, //opera内核
                webKit: u.indexOf('AppleWebKit') > -1, //苹果、谷歌内核
                gecko: u.indexOf('Gecko') > -1 && u.indexOf('KHTML') == -1, //火狐内核
                mobile: !!u.match(/AppleWebKit.*Mobile.*/), //是否为移动终端
                ios: !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/), //ios终端
                android: u.indexOf('Android') > -1 || u.indexOf('Linux') > -1, //android终端或者uc浏览器
                iPhone: u.indexOf('iPhone') > -1 || u.indexOf('Mac') > -1, //是否为iPhone或者QQHD浏览器
                iPad: u.indexOf('iPad') > -1, //是否iPad
                webApp: u.indexOf('Safari') == -1 //是否web应该程序，没有头部与底部
            };
        } (),
        language: (navigator.browserLanguage || navigator.language).toLowerCase()
    }
    console.log("语言版本: " + browser.language);
    console.log(" 是否为移动终端: " + browser.versions.mobile);
    console.log(" ios终端: " + browser.versions.ios);
    console.log(" android终端: " + browser.versions.android);
    console.log(" 是否为iPhone: " + browser.versions.iPhone);
    console.log(" 是否iPad: " + browser.versions.iPad);
    console.log(navigator.userAgent);
    console.log(browser.versions);
```

或者使用[ua-parser-js](https://github.com/faisalman/ua-parser-js)

---
### 6、html5有哪些新特性、移除了那些元素？如何处理HTML5新标签的浏览器兼容问题？如何区分 HTML 和 HTML5？
- HTML5 现在已经不是 SGML 的子集，主要是关于图像，位置，存储，多任务等功能的增加。
- 拖拽释放(Drag and drop) API 
  语义化更好的内容标签（header,nav,footer,aside,article,section）
  音频、视频API(audio,video)
  画布(Canvas) API
  地理(Geolocation) API
  本地离线存储 localStorage 长期存储数据，浏览器关闭后数据不丢失；
  sessionStorage 的数据在浏览器关闭后自动删除
  
  表单控件，calendar、date、time、email、url、search  
  新的技术webworker, websocket, Geolocation
- 移除的元素

纯表现的元素：basefont，big，center，font, s，strike，tt，u；

对可用性产生负面影响的元素：frame，frameset，noframes；

支持HTML5新标签：
- IE8/IE7/IE6支持通过document.createElement方法产生的标签，
  可以利用这一特性让这些浏览器支持HTML5新标签，
  
  浏览器支持新标签后，还需要添加标签默认的样式：
- 当然最好的方式是直接使用成熟的框架、使用最多的是html5shim框架
  
   
- 如何区分： DOCTYPE声明\新增的结构元素\功能元素

---
### 7、简述一下你对HTML语义化的理解？

**什么是HTML语义化？**

　　HTML标签可以分为有语义的标签，和无语义的标签。比如table表示表格，form表示表单，a标签表示超链接，strong标签表强调。无语义标签典型的有<div>,<span>等。HTML语义化我的理解就是在页面中尽量多滴结合场景多使用含有语义的标签，少使用div,span等无语义的标签。

**2、为什么要语义化？**

为了在没有CSS的情况下，页面也能呈现出很好地内容结构、代码结构:为了裸奔时好看；
- 用户体验：例如title、alt用于解释名词或解释图片信息、label标签的活用；
- 有利于SEO：和搜索引擎建立良好沟通，有助于爬虫抓取更多的有效信息：爬虫依赖于标签来确定上下文和各个关键字的权重；
- 方便其他设备解析（如屏幕阅读器、盲人阅读器、移动设备）以意义的方式来渲染网页；
- 便于团队开发和维护，语义化更具可读性，是下一步吧网页的重要动向，遵循W3C标准的团队都遵循这个标准，可以减少差异化。

**3、写HTML代码时应注意什么？**
- 尽可能少的使用无语义的标签div和span；
- 在语义不明显时，既可以使用div或者p时，尽量用p, 因为p在默认情况下有上下间距，对兼容特殊终端有利；
- 不要使用纯样式标签，如：b、font、u等，改用css设置。
- 需要强调的文本，可以包含在strong或者em标签中（浏览器预设样式，能用CSS指定就不用他们），strong默认样式是加粗（不要用b），em是斜体（不用i）；
- 使用表格时，标题要用caption，表头用thead，主体部分用tbody包围，尾部用tfoot包围。表头和一般单元格要区分开，表头用th，单元格用td；
- 表单域要用fieldset标签包起来，并用legend标签说明表单的用途；
- 每个input标签对应的说明文本都需要使用label标签，并且通过为input设置id属性，在lable标签中设置for=someld来让说明文本和相对应的input关联起来。

---
### 9、浏览器是怎么对HTML5的离线储存资源进行管理和加载的呢？

文章一：http://www.codeceo.com/article/html5-cache.html

文章二：http://www.hello-code.com/question/html5/201408/1684.html

文章三：https://segmentfault.com/a/1190000002422341

---
### 10、详说 Cookie, LocalStorage 与 SessionStorage的区别

https://segmentfault.com/a/1190000002723469

---
### 11、iframe优缺点

**iframe的优点：**
- 1.iframe能够原封不动的把嵌入的网页展现出来。
- 2.如果有多个网页引用iframe，那么你只需要修改iframe的内容，就可以实现调用的每一个页面内容的更改，方便快捷。
- 3.网页如果为了统一风格，头部和版本都是一样的，就可以写成一个页面，用iframe来嵌套，可以增加代码的可重用。
- 4.如果遇到加载缓慢的第三方内容如图标和广告，这些问题可以由iframe来解决。

**iframe的缺点**：
- 1.会产生很多页面，不容易管理。
- 2.iframe框架结构有时会让人感到迷惑，如果框架个数多的话，可能会出现上下、左右滚动条，会分散访问者的注意力，用户体验度差。
- 3.代码复杂，无法被一些搜索引擎索引到，这一点很关键，现在的搜索引擎爬虫还不能很好的处理iframe中的内容，所以使用iframe会不利于搜索引擎优化。
- 4.很多的移动设备（PDA 手机）无法完全显示框架，设备兼容性差。
- 5.iframe框架页面会增加服务器的http请求，对于大型网站是不可取的。
- iframe会阻塞主页面的Onload事件；
- frame和主页面共享连接池，而浏览器对相同域的连接有限制，所以会影响页面的并行加载。
- 使用iframe之前需要考虑这两个缺点。如果需要使用iframe，最好是通过javascript；动态给iframe添加src属性值，这样可以可以绕开以上两个问题。

分析了这么多，现在基本上都是用Ajax来代替iframe，所以iframe已经渐渐的退出了前端开发。

---
### 12、Label的作用是什么？是怎么用的？（加 for 或 包裹）

W3C里面关于label的定义和用法如下：
<label> 标签为 input 元素定义标注（标记）。
label 元素不会向用户呈现任何特殊效果。不过，它为鼠标用户改进了可用性。如果您在 label 元素内点击文本，就会触发此控件。就是说，当用户选择该标签时，浏览器就会自动将焦点转到和标签相关的表单控件上。

[《HTML中Div、span、label标签的区别》](http://blog.csdn.net/cui_angel/article/details/7676395)

---
### 13、HTML5的form如何关闭自动完成功能?

`autocomplete`属性（自动完成功能）新属性
<input autocomplete="on/off" />
所谓的自动完成功能就是浏览器帮助记忆之前输入的数据，当再次输入相同数据时，将自动显示之前曾输入的数据作为候补。用户可以选择其中之一。 该内容属性为列举属性。可以指定的值为`on`、`off`。
`on` : autocomplete属性有效
`off`: autocomplete属性无效
`autocomplete`属性的默认值为`on`，即封装了该自动完成功能的浏览器即使没有指定该属性， 也会默认自动完成功能有效。但是出于安全需要，输入的内容不需要浏览器记忆，这时，最好设置自动完成功能无效。
当input元素的`type`属性的值为`text、 search、url、tel、 email、password、 datetime、date、 month、week、time、 datetime-local、number、 range、color`时，可以使用`autocomplete`属性

---
### 14、如何实现浏览器内多个标签页之间的通信?

调用`LocalStorage` 、`Cookies`等本地存储方式

---
### 15、webSocket如何兼容低浏览器

对不兼容的浏览器加载`WebSocket.swf`和`WebSocket.js`文件

Adobe Flash Socket 、 ActiveX HTMLFile (IE) 、 基于 multipart 编码发送 XHR 、 基于长轮询的 XHR

http://www.tuicool.com/articles/EF7Nni
## 
### 16、页面可见性（Page Visibility API） 可以有哪些用途

http://www.zhangxinxu.com/wordpress/2012/11/page-visibility-api-introduction-extend/
http://www.tuicool.com/articles/BfIjYf

---
### 17、如何在页面上实现一个圆形的可点击区域

椭圆点击参考：http://www.cnblogs.com/hongru/p/3187934.html

---
### 18、实现不使用 border 画出1px高的线，在不同浏览器的Quirksmode和CSSCompat模式下都能保持同一效果

……

---
### 19、网页验证码是干嘛的，是为了解决什么安全问题

[验证码对抗之路及现有验证机制介绍](http://weibo.com/ttarticle/p/show?id=2309403986263437891540)

---
### 20、tite与h1的区别、b与strong的区别、i与em的区别

[网站SEO优化中tilte与h1的区别、b与strong的区别、i与em的区别](http://www.zhaojunseo.com/780.html)

[em和strong的区别](https://segmentfault.com/a/1190000002481725)

[b标签、Strong标签、h1标签的区别以及使用](http://blog.csdn.net/msg_java2011/article/details/6456442)

---

The End 
Create by @giscafer
To be continued

**Comment by missfoxw** [comment]
"获取浏览器信息的片段代码有点问题

**Comment by giscafer** [comment]
@missfoxw 感谢指出，ua的可以参考别的库，比如 [ua-parser-js](https://github.com/faisalman/ua-parser-js)
