### ISSUE TITLE
不是Github Issues作为来源吗，这个【使用faunadb云端数据库存储】又是什么？

### ISSUE THREAD

**Issue by lopins** [giscafer/blog#70]
不是Github Issues作为来源吗，这个【使用faunadb云端数据库存储】又是什么？

https://github.com/giscafer/blog/blob/30deb441e1ce7865d343f55862274a8a860ba5cb/README.md?plain=1#L12

**Comment by giscafer** [comment]
存储的每个文章点赞数量而已。其他没啥用，也可以去掉。文章都是issue
